defmodule BacView.BACnet.Protocol.EngineeringUnits do
  @moduledoc """
  Display helpers for BACnet engineering units.

  - `symbol/1` returns compact unit symbols for value formatting (e.g. `°C`, `%`).
  - `label/1` returns human-readable text for property display.
  """

  @symbols %{
    ampere_seconds: "A·s",
    ampere_square_hours: "A²·h",
    ampere_square_meters: "A·m²",
    amperes: "A",
    amperes_per_meter: "A/m",
    amperes_per_square_meter: "A/m²",
    bars: "bar",
    becquerels: "Bq",
    btus: "BTU",
    btus_per_hour: "BTU/h",
    btus_per_pound: "BTU/lb",
    btus_per_pound_dry_air: "BTU/lb",
    candelas: "cd",
    candelas_per_square_meter: "cd/m²",
    centimeters: "cm",
    centimeters_of_mercury: "cmHg",
    centimeters_of_water: "cmH₂O",
    cubic_feet: "ft³",
    cubic_feet_per_day: "ft³/d",
    cubic_feet_per_hour: "ft³/h",
    cubic_feet_per_minute: "CFM",
    cubic_feet_per_second: "ft³/s",
    cubic_meters: "m³",
    cubic_meters_per_day: "m³/d",
    cubic_meters_per_hour: "m³/h",
    cubic_meters_per_minute: "m³/min",
    cubic_meters_per_second: "m³/s",
    currency1: "¤1",
    currency10: "¤10",
    currency2: "¤2",
    currency3: "¤3",
    currency4: "¤4",
    currency5: "¤5",
    currency6: "¤6",
    currency7: "¤7",
    currency8: "¤8",
    currency9: "¤9",
    cycles_per_hour: "c/h",
    cycles_per_minute: "c/min",
    days: "d",
    decibels: "dB",
    decibels_a: "dB(A)",
    decibels_millivolt: "dBmV",
    decibels_volt: "dBV",
    degree_days_celsius: "°C·d",
    degree_days_fahrenheit: "°F·d",
    degrees_angular: "°",
    degrees_celsius: "°C",
    degrees_celsius_per_hour: "°C/h",
    degrees_celsius_per_minute: "°C/min",
    degrees_fahrenheit: "°F",
    degrees_fahrenheit_per_hour: "°F/h",
    degrees_fahrenheit_per_minute: "°F/min",
    degrees_kelvin: "K",
    degrees_kelvin_per_hour: "K/h",
    degrees_kelvin_per_minute: "K/min",
    degrees_phase: "°",
    delta_degrees_fahrenheit: "Δ°F",
    delta_degrees_kelvin: "ΔK",
    farads: "F",
    feet: "ft",
    feet_per_minute: "ft/min",
    feet_per_second: "ft/s",
    foot_candles: "fc",
    grams: "g",
    grams_of_water_per_kilogram_dry_air: "g/kg",
    grams_per_cubic_centimeter: "g/cm³",
    grams_per_cubic_meter: "g/m³",
    grams_per_gram: "g/g",
    grams_per_kilogram: "g/kg",
    grams_per_liter: "g/L",
    grams_per_milliliter: "g/mL",
    grams_per_minute: "g/min",
    grams_per_second: "g/s",
    grams_per_square_meter: "g/m²",
    gray: "Gy",
    hectopascals: "hPa",
    henrys: "H",
    hertz: "Hz",
    horsepower: "hp",
    hours: "h",
    hundredths_seconds: "cs",
    imperial_gallons: "imp gal",
    imperial_gallons_per_minute: "imp gal/min",
    inches: "in",
    inches_of_mercury: "inHg",
    inches_of_water: "inH₂O",
    joule_per_hours: "J/h",
    joule_seconds: "J·s",
    joules: "J",
    joules_per_cubic_meter: "J/m³",
    joules_per_degree_kelvin: "J/K",
    joules_per_kilogram_degree_kelvin: "J/(kg·K)",
    joules_per_kilogram_dry_air: "J/kg",
    kilo_btus: "kBTU",
    kilo_btus_per_hour: "kBTU/h",
    kilobecquerels: "kBq",
    kilograms: "kg",
    kilograms_per_cubic_meter: "kg/m³",
    kilograms_per_hour: "kg/h",
    kilograms_per_kilogram: "kg/kg",
    kilograms_per_minute: "kg/min",
    kilograms_per_second: "kg/s",
    kilohertz: "kHz",
    kilohms: "kΩ",
    kilojoules: "kJ",
    kilojoules_per_degree_kelvin: "kJ/K",
    kilojoules_per_kilogram: "kJ/kg",
    kilojoules_per_kilogram_dry_air: "kJ/kg",
    kilometers: "km",
    kilometers_per_hour: "km/h",
    kilopascals: "kPa",
    kilovolt_ampere_hours: "kVAh",
    kilovolt_ampere_hours_reactive: "kVARh",
    kilovolt_amperes: "kVA",
    kilovolt_amperes_reactive: "kVAR",
    kilovolts: "kV",
    kilowatt_hours: "kWh",
    kilowatt_hours_per_square_foot: "kWh/ft²",
    kilowatt_hours_per_square_meter: "kWh/m²",
    kilowatt_hours_reactive: "kVARh",
    kilowatts: "kW",
    liters: "L",
    liters_per_hour: "L/h",
    liters_per_minute: "L/min",
    liters_per_second: "L/s",
    lumens: "lm",
    luxes: "lx",
    mega_btus: "MBTU",
    megabecquerels: "MBq",
    megahertz: "MHz",
    megajoules: "MJ",
    megajoules_per_degree_kelvin: "MJ/K",
    megajoules_per_kilogram_dry_air: "MJ/kg",
    megajoules_per_square_foot: "MJ/ft²",
    megajoules_per_square_meter: "MJ/m²",
    megavolt_ampere_hours: "MVAh",
    megavolt_ampere_hours_reactive: "MVARh",
    megavolt_amperes: "MVA",
    megavolt_amperes_reactive: "MVAR",
    megavolts: "MV",
    megawatt_hours: "MWh",
    megawatt_hours_reactive: "MVARh",
    megawatts: "MW",
    megohms: "MΩ",
    meters: "m",
    meters_per_hour: "m/h",
    meters_per_minute: "m/min",
    meters_per_second: "m/s",
    meters_per_second_per_second: "m/s²",
    micrograms_per_cubic_meter: "μg/m³",
    micrograms_per_liter: "μg/L",
    microgray: "μGy",
    micrometers: "μm",
    microsiemens: "μS",
    microsieverts: "μSv",
    microsieverts_per_hour: "μSv/h",
    miles_per_hour: "mph",
    milliamperes: "mA",
    millibars: "mbar",
    milligrams: "mg",
    milligrams_per_cubic_meter: "mg/m³",
    milligrams_per_gram: "mg/g",
    milligrams_per_kilogram: "mg/kg",
    milligrams_per_liter: "mg/L",
    milligray: "mGy",
    milliliters: "mL",
    milliliters_per_second: "mL/s",
    millimeters: "mm",
    millimeters_of_mercury: "mmHg",
    millimeters_of_water: "mmH₂O",
    millimeters_per_minute: "mm/min",
    millimeters_per_second: "mm/s",
    milliohms: "mΩ",
    million_standard_cubic_feet_per_day: "MMSCFD",
    million_standard_cubic_feet_per_minute: "MMSCFM",
    millirems: "mrem",
    millirems_per_hour: "mrem/h",
    milliseconds: "ms",
    millisiemens: "mS",
    millisieverts: "mSv",
    millivolts: "mV",
    milliwatts: "mW",
    minutes: "min",
    minutes_per_degree_kelvin: "min/K",
    mole_percent: "mol%",
    months: "mo",
    nanograms_per_cubic_meter: "ng/m³",
    nephelometric_turbidity_unit: "NTU",
    newton: "N",
    newton_meters: "N·m",
    newton_seconds: "N·s",
    newtons_per_meter: "N/m",
    no_units: "",
    ohm_meter_squared_per_meter: "Ω·m²/m",
    ohm_meters: "Ω·m",
    ohms: "Ω",
    parts_per_billion: "ppb",
    parts_per_million: "ppm",
    pascal_seconds: "Pa·s",
    pascals: "Pa",
    per_hour: "/h",
    per_mille: "‰",
    per_minute: "/min",
    per_second: "/s",
    percent: "%",
    percent_obscuration_per_foot: "%/ft",
    percent_obscuration_per_meter: "%/m",
    percent_per_second: "%/s",
    percent_relative_humidity: "%RH",
    ph: "pH",
    pounds_force_per_square_inch: "psi",
    pounds_mass: "lb",
    pounds_mass_per_day: "lb/d",
    pounds_mass_per_hour: "lb/h",
    pounds_mass_per_minute: "lb/min",
    pounds_mass_per_second: "lb/s",
    power_factor: "PF",
    psi_per_degree_fahrenheit: "psi/°F",
    radians: "rad",
    radians_per_second: "rad/s",
    revolutions_per_minute: "RPM",
    seconds: "s",
    siemens: "S",
    siemens_per_meter: "S/m",
    sieverts: "Sv",
    square_centimeters: "cm²",
    square_feet: "ft²",
    square_inches: "in²",
    square_meters: "m²",
    square_meters_per_newton: "m²/N",
    standard_cubic_feet_per_day: "SCFD",
    teslas: "T",
    therms: "therm",
    thousand_cubic_feet_per_day: "MCFD",
    thousand_standard_cubic_feet_per_day: "MMSCFD",
    ton_hours: "ton·h",
    tons: "t",
    tons_per_hour: "t/h",
    tons_refrigeration: "TR",
    us_gallons: "US gal",
    us_gallons_per_hour: "US gal/h",
    us_gallons_per_minute: "US gal/min",
    volt_ampere_hours: "VAh",
    volt_ampere_hours_reactive: "VARh",
    volt_amperes: "VA",
    volt_amperes_reactive: "VAR",
    volt_square_hours: "V²·h",
    volts: "V",
    volts_per_degree_kelvin: "V/K",
    volts_per_meter: "V/m",
    watt_hours: "Wh",
    watt_hours_per_cubic_meter: "Wh/m³",
    watt_hours_reactive: "VARh",
    watts: "W",
    watts_per_meter_per_degree_kelvin: "W/(m·K)",
    watts_per_square_foot: "W/ft²",
    watts_per_square_meter: "W/m²",
    watts_per_square_meter_degree_kelvin: "W/(m²·K)",
    webers: "Wb",
    weeks: "wk",
    years: "yr"
  }

  @spec symbol(atom() | String.t() | nil) :: String.t()
  def symbol(nil), do: ""
  def symbol(:no_units), do: ""
  def symbol(unit) when is_binary(unit), do: unit

  def symbol(unit) when is_atom(unit) do
    Map.get(@symbols, unit, Atom.to_string(unit))
  end

  @spec label(atom() | String.t() | nil) :: String.t()
  def label(nil), do: "—"
  def label(:no_units), do: "No units"
  def label(unit) when is_binary(unit), do: unit

  def label(unit) when is_atom(unit) do
    unit
    |> Atom.to_string()
    |> String.replace("_", " ")
    |> titleize()
  end

  defp titleize(str) do
    str
    |> String.split(" ", trim: true)
    |> Enum.map_join(" ", &String.capitalize/1)
  end
end
