defmodule BacViewWeb.Endpoint.CompileHelper do
  @moduledoc false

  @desktop_mode Application.compile_env(:bacview, :desktop_mode)

  # Workaround to compile errors that expands `use` before the `if`
  defmacro use_endpoint() do
    if @desktop_mode do
      quote do
        use Desktop.Endpoint, otp_app: :bacview
      end
    else
      quote do
        use Phoenix.Endpoint, otp_app: :bacview
      end
    end
  end
end

defmodule BacViewWeb.Endpoint do
  @desktop_mode Application.compile_env(:bacview, :desktop_mode)

  # Workaround to compile errors that expands `use` before the `if`
  import BacViewWeb.Endpoint.CompileHelper, only: [use_endpoint: 0]
  use_endpoint()

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options (if @desktop_mode do
                      [
                        store: :ets,
                        key: "_bacview_key",
                        table: :bacview_session
                      ]
                    else
                      [
                        store: :cookie,
                        key: "_bacview_key",
                        signing_salt: "Zq3u03aF",
                        same_site: "Lax"
                      ]
                    end)

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :bacview,
    gzip: not code_reloading?,
    only: BacViewWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)

  # Maybe also needs "and not code_reloading?"
  if @desktop_mode do
    plug(Desktop.Auth)
  end

  plug(BacViewWeb.Router)
end
